WebNotes/Models/ErrorViewModel.cs
using System;

namespace WebNotes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebNotes/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebNotes.Models;

namespace WebNotes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebNotes/Controllers/PageController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Parser;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using Microsoft.Extensions.Configuration;

namespace WebNotes.Controllers
{
    public class PageController : Controller
    {
        private readonly IConfiguration _config;
        private readonly MarkdownParser _parser;
        //private string pathToSource = "bin/Debug/netcoreapp3.1/source";

        private FileInfo file;

        public PageController(IConfiguration config, MarkdownParser parser)
        {
            _config = config;
            _parser = parser;
        }

        public ActionResult Index(string book ,string page = "index.md")
        {
            if (book == null)
            {
                book = GetDefaultBook();
            }
            if (page == null)
            {
                page = "index.md";
            }

            ViewBag.Book = book;
            ViewBag.Page = page;
            ViewBag.Summary = string.Format(_parser.ParseTableOfContents(GetFullPath(book, "SUMMARY.md")) + "</div></div>",null, null, book);
            return View("TableOfContents");
        }

        [HttpGet]
        // <img class="img-fluid" src="https://localhost:44372/Page/Image?book=TestBook&path=source/vim.jpg"/>
        public IActionResult Image(string book, string path) 
        {
            // Works with types: jpg, png, bmp, gif and other

            file = new FileInfo(GetFullPath(book, path));

            if (file.Exists)
            {
                var b = System.IO.File.ReadAllBytes(file.FullName);
                string info = "image/" + file.Extension.Replace(".", "");
                return File(b, info);
            }
            else
            {
                return base.Content("Image not found.", "text/html");
            }
        }

        [Route("Page/Media")]
        // https://localhost:44372/Page/Video?book=TestBook&path=source/v.mp4
        public FileResult VideoAndAudio(string book, string path)
        {
            file = new FileInfo(GetFullPath(book, path));

            if (file.Exists)
            {
                return PhysicalFile(file.FullName, "application/octet-stream", enableRangeProcessing: true);
            }

            return null;
        }

        private string GetFullPath(string book, string path)
        {
            return $"{_config["SourcePath"]}/{book}/{path}";
        }

        /*public ActionResult TestPage()
        {
            ViewBag.Html = _parser.ParsePage("index.md");
            return View("Content");
        }*/

        [HttpGet]
        public ActionResult Get(string book, string page = "index.md")
        {
            ViewBag.Html = _parser.ParsePage(GetFullPath(book, page));
            return View("Content");
        }

        private string GetDefaultBook()
        {
            DirectoryInfo info = new DirectoryInfo(Directory.GetCurrentDirectory()+ _config["SourcePath"]);
            return info.GetDirectories()[0].Name;
        }

        /*[HttpGet]
        public ContentResult Get(string page = "index.md")
        {
            base.Content("<h1>Tag</h1>text", "text/html");
        }*/

     }
}

WebNotes/Views/Home/Index.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

@for (int i=0;i<10;i++)
{
    <h1>@i</h1>
}

WebNotes/Views/Page/Content.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    //Layout = "_PageLayout";
}

<html>
<head>
    <meta charset="utf-8">
    <title>GitBook</title>
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon">

    <link rel="stylesheet" type="text/css" href="~/css/style.css">
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">

    <script src="~/js/jquery-3.2.1.slim.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/video.js"></script>
    <!--<script src="~/js/sidebar.js"></script>-->
</head>
<body>
    <div class="cus_body">
        <div id="accordion_chapters" class="mt-3">
            @Html.Raw(@ViewBag.Html)
        </div>
    </div>
</body>
</html>

WebNotes/Views/Page/TableOfContents.cshtml
@*
    Test Menu need to replace to dynamic
*@
@{
    Layout = "_PageLayout";
}

@Html.Raw(@ViewBag.Summary)

WebNotes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebNotes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebNotes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebNotes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebNotes/Views/Shared/_PageLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <title>GitBook</title>
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon">

    <link rel="stylesheet" type="text/css" href="~/css/style.css">
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">

    <script src="~/js/jquery-3.2.1.slim.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/video.js"></script>
    <script src="~/js/sidebar.js"></script>
    <script src="~/js/pageLoader.js"></script>
</head>
<body>
    <div class="container-fluid h-100">
        <div class="row h-100">

            <div class=" bg-light scroll" id="sidebar">
                <!--col-sm-2-->
                @RenderBody()

            </div>

            <img id="closebtn" src="~/img/menu.svg" onclick="openNav()" />

            <div class="col-sm h-100">
                <!--scroll-->
                <!--@Html.ActionLink("", "Get", "Page", new { page = "index.md" }, null);-->
                <iframe id="page" src="/Page/Get?book=@ViewBag.Book&page=@ViewBag.Page">
                </iframe>
            </div>
        </div>
    </div>
</body>
</html>